project:
  # Set whether or not merge requests can be merged with skipped jobs. Type: boolean
  allow_merge_on_skipped_pipeline: null
  # How many approvers should approve merge request by default. To configure
  # approval rules, see Merge request approvals API. Type: integer
  approvals_before_merge: 0
  # Auto-cancel pending pipelines. This isn't a boolean, but enabled/disabled. Type:
  # string
  auto_cancel_pending_pipelines: enabled
  # Auto Deploy strategy (continuous, manual, or timed_incremental). Type: string
  auto_devops_deploy_strategy: continuous
  # Enable Auto DevOps for this project. Type: boolean
  auto_devops_enabled: false
  # Set whether auto-closing referenced issues on default branch. Type: boolean
  autoclose_referenced_issues: true
  # Test coverage parsing. Type: string
  build_coverage_regex: 'coverage: \d+\.\d+% of statements'
  # The Git strategy. Defaults to fetch. Type: string
  build_git_strategy: fetch
  # The maximum amount of time, in seconds, that a job can run. Type: integer
  build_timeout: 3600
  # One of disabled, private, or enabled. Type: string
  builds_access_level: enabled
  # The path to CI configuration file. Type: string
  ci_config_path: ""
  # Default number of revisions for shallow cloning. Type: integer
  ci_default_git_depth: 50
  # When a new deployment job starts, skip older deployment jobs that are still
  # pending. Type: boolean
  ci_forward_deployment_enabled: true
  # Update the image cleanup policy for this project. Accepts: cadence (string),
  # keep_n (integer), older_than (string), name_regex (string), name_regex_delete
  # (string), name_regex_keep (string), enabled (boolean). Type: hash
  container_expiration_policy:
    cadence: 1d
    enabled: false
    keep_n: 10
    name_regex_delete: .*
    name_regex_keep: null
    older_than: 90d
  # Set visibility of container registry, for this project, to one of disabled,
  # private or enabled. Type: string
  container_registry_access_level: disabled
  # The default branch name. Type: string
  default_branch: main
  # Short project description. Type: string
  description: Utilities for processing Wikipedia dumps in Go. https://pkg.go.dev/gitlab.com/tozd/go/mediawiki
  # Disable email notifications. Type: boolean
  emails_disabled: false
  # The classification label for the project. Type: string
  external_authorization_classification_label: ""
  # One of disabled, private, or enabled. Type: string
  forking_access_level: enabled
  # One of disabled, private, or enabled. Type: string
  issues_access_level: enabled
  # Default description for Issues. Description is parsed with GitLab Flavored
  # Markdown. See Templates for issues and merge requests. Type: string
  issues_template: null
  # Disable or enable the ability to keep the latest artifact for this project.
  # Type: boolean
  keep_latest_artifact: true
  # Enable LFS. Type: boolean
  lfs_enabled: true
  # Template used to create merge commit message in merge requests. (Introduced in
  # GitLab 14.5.) Type: string
  merge_commit_template: null
  # Set the merge method used. Type: string
  merge_method: merge
  # Enable or disable merge pipelines. Type: boolean
  merge_pipelines_enabled: false
  # One of disabled, private, or enabled. Type: string
  merge_requests_access_level: enabled
  # Default description for Merge Requests. Description is parsed with GitLab
  # Flavored Markdown. See Templates for issues and merge requests. Type: string
  merge_requests_template: null
  # Enable or disable merge trains. Type: boolean
  merge_trains_enabled: false
  # Set whether merge requests can only be merged when all the discussions are
  # resolved. Type: boolean
  only_allow_merge_if_all_discussions_are_resolved: false
  # Set whether merge requests can only be merged with successful jobs. Type:
  # boolean
  only_allow_merge_if_pipeline_succeeds: false
  # One of disabled, private, or enabled. Type: string
  operations_access_level: disabled
  # Enable or disable packages repository feature. Type: boolean
  packages_enabled: false
  # One of disabled, private, enabled, or public. Type: string
  pages_access_level: enabled
  # Show link to create/view merge request when pushing from the command line. Type:
  # boolean
  printing_merge_request_link_enabled: true
  # If true, jobs can be viewed by non-project members. Type: boolean
  public_jobs: true
  # Enable Delete source branch option by default for all new merge requests. Type:
  # boolean
  remove_source_branch_after_merge: true
  # One of disabled, private, or enabled. Type: string
  repository_access_level: enabled
  # Allow users to request member access. Type: boolean
  request_access_enabled: true
  # Automatically resolve merge request diffs discussions on lines changed with a
  # push. Type: boolean
  resolve_outdated_diff_discussions: false
  # Allow only users with the Maintainer role to pass user-defined variables when
  # triggering a pipeline. For example when the pipeline is triggered in the UI,
  # with the API, or by a trigger token. Type: boolean
  restrict_user_defined_variables: false
  # Enable or disable Service Desk feature. Type: boolean
  service_desk_enabled: true
  # Enable shared runners for this project. Type: boolean
  shared_runners_enabled: true
  # One of disabled, private, or enabled. Type: string
  snippets_access_level: disabled
  # Template used to create squash commit message in merge requests. (Introduced in
  # GitLab 14.6.) Type: string
  squash_commit_template: null
  # One of never, always, default_on, or default_off. Type: string
  squash_option: default_off
  # The commit message used to apply merge request suggestions. Type: string
  suggestion_commit_message: null
  # The list of topics for the project. This replaces any existing topics that are
  # already added to the project. (Introduced in GitLab 14.0.) Type: array
  topics: []
  # One of disabled, private, or enabled. Type: string
  wiki_access_level: disabled
avatar: ""
# expires_at: Share expiration date in ISO 8601 format: 2016-09-26. Type: string
# group_access: The access level to grant the group. Type: integer
# group_id: The ID of the group to share with. Type: integer
shared_with_groups: []
forked_from_project: 0
# color: The color of the label given in 6-digit hex notation with leading '#'
# sign (for example, #FFAABB) or one of the CSS color names. Type: string
# description: The description of the label. Type: string
# id: The ID or title of a group's label. Type: integer or string
# name: The name of the label. Type: string
# priority: The priority of the label. Must be greater or equal than zero or null
# to remove the priority. Type: integer
labels: []
# allow_force_push: Allow all users with push access to force push. (default:
# false) Type: boolean
# allowed_to_merge: Array of access levels allowed to merge, with each described
# by a hash of the form {user_id: integer}, {group_id: integer}, or {access_level:
# integer}. Type: array
# allowed_to_push: Array of access levels allowed to push, with each described by
# a hash of the form {user_id: integer}, {group_id: integer}, or {access_level:
# integer}. Type: array
# allowed_to_unprotect: Array of access levels allowed to unprotect, with each
# described by a hash of the form {user_id: integer}, {group_id: integer}, or
# {access_level: integer}. Type: array
# code_owner_approval_required: Prevent pushes to this branch if it matches an
# item in the CODEOWNERS file. (defaults: false) Type: boolean
# name: The name of the branch or wildcard. Type: string
protected_branches:
  - allow_force_push: false
    allowed_to_merge:
      # Maintainers
      - access_level: 40
        group_id: null
        user_id: null
    allowed_to_push:
      # Maintainers
      - access_level: 40
        group_id: null
        user_id: null
    allowed_to_unprotect: []
    code_owner_approval_required: false
    name: main
# environment_scope: The environment_scope of the variable. Default: *. Type:
# string
# key: The key of a variable; must have no more than 255 characters; only A-Z,
# a-z, 0-9, and _ are allowed. Type: string
# masked: Whether the variable is masked. Default: false. Type: boolean
# protected: Whether the variable is protected. Default: false. Type: boolean
# value: The value of a variable. Type: string
# variable_type: The type of a variable. Available types are: env_var (default)
# and file. Type: string
variables:
  - environment_scope: '*'
    key: GITLAB_API_TOKEN
    masked: true
    protected: true
    # sops:enc
    value: ENC[AES256_GCM,data:7d2dyddnJNOFIOw5HYhh9JBG28fI40mDqxI=,iv:xFat29+OXDWA3X+85DZlZn3SRv8QIKbM9cgDHaTxpHg=,tag:IPejY8TYsVGlN2pVHXv0ng==,type:str]
    variable_type: env_var
  - environment_scope: '*'
    key: SOPS_AGE_KEY_FILE
    masked: false
    protected: true
    # sops:enc
    value: ENC[AES256_GCM,data:xypKfV0nWb5Jlz7o5I7cZRpqvIBrMn/LZuTE+3YzWoXyuwtj3fKkUusJ/9P67iHJra2HSAeJvfN+6zggeGrrHYpqcv3CNurSxk0a5oCuKS4glzYpQNEUX03nJWANEGKGGUveR0l7ZPB0C/h1TzIWZwCINSCDBaZN5Uo8BRiPJeEj17BfLh66B93PiYDab85eZe/CVVONAV++nXmLadD9pqgspeDdRSxF/4J/ICmNqErnM0lI9N+PLjH0Qtj2,iv:8QTphbY9db4xMz20VasFe9MB+jqs5Aylpd+1PWcbgk8=,tag:O3CEc+br+pNikxPlTOAU5A==,type:str]
    variable_type: file
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1txs7q5kagh2kjpz9g7uznyn9hhhy4pjktq9lj2cghv5ns3stfs3sl4qg59
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMVhBb1JpV1ZLckF1Yzlj
        M3E3TDdkUTNxMGF3SWYwaWRzUndOZE9OMVJBCk9kZGdaM2V1eTE4VWV0TGJxUW9a
        WUtITy9BMXV4YXV3RGdhVEVWRU8zencKLS0tIDE0ZHhpbmdHWmt6ZThKbFl5cjZ6
        Kzh0VmdhRjYrNmRJWE13MlhGUHZwU2MKjPEZ3tCzJ+ewSY//QhyIng209KWIRVjS
        BAYEbTdTbUhCMtbw49PQ4Sh8U8zJoPcZxJsMI8Avz+Ser76ULo4B/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2022-01-05T21:50:35Z"
  mac: ENC[AES256_GCM,data:Y4mQ1Cw27vNGegUi6TSFXaEjleOD76SWmLfBqGFuO5tPspKP2o6W1FUd3Haro1DMuRZcqcA5h2L4cPzH2nKarLFTEcrtAtdt00FgLf3QPo+NyvgAg5lzPDGnUkkmOa/LHb43ZvLB0BtxHPaYAjndhff8dodNP4QdtMJV6nOHhRg=,iv:7hvWVUmU84Ffm3hUfZEus8hk/oXac7RJ8X1pmS0lH4U=,tag:SGkEiJu25I3jVB7IMjqbYg==,type:str]
  pgp: []
  encrypted_comment_regex: sops:enc
  mac_only_encrypted: true
  version: 3.7.1
